server:
  port: 9092


spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf8&serverTimezone=UTC
